from __future__ import annotations

from datetime import date
from typing import Protocol

from app.config import ENABLE_LLM
from app.output_context import (
    OutputGenerationError,
    build_output_context,
    format_money,
)
from app.quotation_models import ApprovalStatus, EmailOutput, QuotationWorkflowState


class WordingRewriter(Protocol):
    def rewrite(self, email: EmailOutput) -> EmailOutput:
        """Rewrite wording without changing structured quotation facts."""


def generate_internal_approval_email(
    state: QuotationWorkflowState,
    *,
    rewriter: WordingRewriter | None = None,
    enable_llm: bool | None = None,
    as_of: date | None = None,
) -> EmailOutput:
    context = build_output_context(state, as_of=as_of)
    reasons = "\n".join(f"- {reason}" for reason in context.review_reasons)
    subject = f"Approval requested: quotation {context.quotation_id}"
    body = (
        "Hello Approver,\n\n"
        "Please review the following quotation proposal.\n\n"
        f"Quotation ID: {context.quotation_id}\n"
        f"Customer: {context.customer_name}\n"
        f"Product: {context.product_description} ({context.product_id})\n"
        f"Quantity: {context.quantity}\n"
        "Recommended unit price: "
        f"{format_money(context.recommended_unit_price, context.currency)}\n"
        "Final proposed unit price: "
        f"{format_money(context.final_unit_price, context.currency)}\n"
        f"Internal margin summary: {context.margin_summary}\n"
        f"Pricing confidence: {context.confidence}\n"
        f"Validation status: {context.validation_status}\n\n"
        f"Review reasons:\n{reasons}\n\n"
        f"Requested action: {context.requested_action}\n\n"
        "This message was generated by the deterministic quotation demo."
    )
    output = EmailOutput("internal_approval_request", subject, body)
    protected = _common_protected_values(context) + (
        format_money(context.recommended_unit_price, context.currency),
        format_money(context.final_unit_price, context.currency),
        context.margin_summary,
        context.validation_status,
    )
    return _maybe_rewrite(output, protected, rewriter, enable_llm)


def generate_reminder_email(
    state: QuotationWorkflowState,
    *,
    rewriter: WordingRewriter | None = None,
    enable_llm: bool | None = None,
    as_of: date | None = None,
) -> EmailOutput:
    if state.approval.status != ApprovalStatus.PENDING_REVIEW:
        raise OutputGenerationError(
            "A reminder email is available only while review is pending."
        )
    context = build_output_context(state, as_of=as_of)
    due_at = state.approval.reminder_due_at
    if due_at is None:
        raise OutputGenerationError("The approval reminder due time is unavailable.")
    due_text = due_at.isoformat()
    subject = f"Reminder: quotation {context.quotation_id} awaits review"
    body = (
        "Hello Approver,\n\n"
        "This is a simulated two-day reminder. The quotation below is still "
        "awaiting review.\n\n"
        f"Quotation ID: {context.quotation_id}\n"
        f"Customer: {context.customer_name}\n"
        f"Product: {context.product_description} ({context.product_id})\n"
        f"Quantity: {context.quantity}\n"
        "Proposed unit price: "
        f"{format_money(context.final_unit_price, context.currency)}\n"
        f"Reminder due at: {due_text}\n"
        f"Validation status: {context.validation_status}\n\n"
        f"Requested action: {context.requested_action}\n\n"
        "No email has been sent; this is a deterministic demo preview."
    )
    output = EmailOutput("internal_two_day_reminder", subject, body)
    protected = _common_protected_values(context) + (
        format_money(context.final_unit_price, context.currency),
        due_text,
        context.validation_status,
    )
    return _maybe_rewrite(output, protected, rewriter, enable_llm)


def generate_customer_email(
    state: QuotationWorkflowState,
    *,
    rewriter: WordingRewriter | None = None,
    enable_llm: bool | None = None,
    as_of: date | None = None,
) -> EmailOutput:
    context = build_output_context(state, require_approved=True, as_of=as_of)
    subject = f"Quotation {context.quotation_id} for {context.customer_name}"
    body = (
        f"Dear {context.customer_name},\n\n"
        "Thank you for the opportunity to provide this quotation. Please find "
        "the approved commercial summary below.\n\n"
        f"Quotation reference: {context.quotation_id}\n"
        f"Product: {context.product_description} ({context.product_id})\n"
        f"Quantity: {context.quantity}\n"
        "Approved unit price: "
        f"{format_money(context.final_unit_price, context.currency)}\n"
        f"Approved total: {format_money(context.total_price, context.currency)}\n"
        f"Quotation valid until: {context.validity_date.isoformat()}\n"
        f"Incoterm: {context.incoterm}\n"
        f"Delivery: {context.delivery_assumption}\n\n"
        "This demo quotation is subject to final company confirmation. Please "
        "contact us if you would like to discuss the proposed configuration.\n\n"
        "Kind regards,\nQuotation Team"
    )
    output = EmailOutput("customer_quotation", subject, body)
    protected = _common_protected_values(context) + (
        format_money(context.final_unit_price, context.currency),
        format_money(context.total_price, context.currency),
        context.validity_date.isoformat(),
        context.incoterm,
    )
    return _maybe_rewrite(output, protected, rewriter, enable_llm)


def generate_revision_email(
    state: QuotationWorkflowState,
    *,
    rewriter: WordingRewriter | None = None,
    enable_llm: bool | None = None,
    as_of: date | None = None,
) -> EmailOutput:
    if state.approval.status not in {
        ApprovalStatus.REJECTED,
        ApprovalStatus.REVISION_REQUESTED,
    }:
        raise OutputGenerationError(
            "A revision notification requires a rejected or revision-requested "
            "quotation."
        )
    context = build_output_context(state, as_of=as_of)
    action = (
        "rejected"
        if state.approval.status == ApprovalStatus.REJECTED
        else "returned for revision"
    )
    reason = state.approval.reason
    subject = f"Quotation {context.quotation_id} {action}"
    body = (
        "Hello,\n\n"
        f"Quotation {context.quotation_id} for {context.customer_name} was "
        f"{action}.\n\n"
        f"Product: {context.product_description} ({context.product_id})\n"
        f"Quantity: {context.quantity}\n"
        f"Status: {state.approval.status.value}\n"
        f"Reason: {reason}\n\n"
        "Please update the quotation and rerun pricing and validation before "
        "submitting it again."
    )
    output = EmailOutput("rejection_revision_notification", subject, body)
    protected = _common_protected_values(context) + (
        state.approval.status.value,
        reason,
    )
    return _maybe_rewrite(output, protected, rewriter, enable_llm)


def _common_protected_values(context) -> tuple[str, ...]:
    return (
        context.quotation_id,
        context.customer_name,
        context.product_id,
        context.product_description,
        str(context.quantity),
        context.currency,
    )


def _maybe_rewrite(
    deterministic: EmailOutput,
    protected_values: tuple[str, ...],
    rewriter: WordingRewriter | None,
    enable_llm: bool | None,
) -> EmailOutput:
    use_rewriter = ENABLE_LLM if enable_llm is None else enable_llm
    if not use_rewriter or rewriter is None:
        return deterministic
    rewritten = rewriter.rewrite(deterministic)
    if rewritten.email_type != deterministic.email_type:
        return deterministic
    combined = f"{rewritten.subject}\n{rewritten.body}"
    if any(value and value not in combined for value in protected_values):
        return deterministic
    return rewritten
