"""initial internal MVP schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-04 07:51:53.120052
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.types


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('roles', app.db.types.JSONDocument(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pricing_data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('published_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=300), nullable=False),
    sa.Column('customer_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('incoterm', sa.String(length=50), nullable=False),
    sa.Column('delivery_location', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pricing_data_version_id', sa.Integer(), nullable=True),
    sa.Column('state_document', app.db.types.JSONDocument(), nullable=False),
    sa.Column('state_schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pricing_data_version_id'], ['pricing_data_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('ix_quotations_owner_user_id', ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_quotation_id'), ['quotation_id'], unique=True)
        batch_op.create_index('ix_quotations_status', ['status'], unique=False)

    op.create_table('approval_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_approver_name', sa.String(length=200), nullable=False),
    sa.Column('assigned_approver_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('reminder_due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('decided_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tasks_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index('ix_approval_tasks_status', ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('quotation_reference', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.String(length=50), nullable=False),
    sa.Column('after_state', sa.String(length=50), nullable=False),
    sa.Column('changed_fields', app.db.types.JSONDocument(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('triggered_rule_ids', app.db.types.JSONDocument(), nullable=False),
    sa.Column('details', app.db.types.JSONDocument(), nullable=False),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_event_type', ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('commercial_validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('result_json', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commercial_validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_validation_runs_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('email_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('queued_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('sent_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_records_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_documents_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('pricing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version', sa.Integer(), nullable=False),
    sa.Column('pricing_data_version_id', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('recommended_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('confidence_label', sa.String(length=50), nullable=False),
    sa.Column('result_json', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_data_version_id'], ['pricing_data_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_runs_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('quotation_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=120), nullable=False),
    sa.Column('internal_description', sa.Text(), nullable=False),
    sa.Column('customer_description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('proposed_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('approved_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('list_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id', 'position', name='uq_line_item_position')
    )
    with op.batch_alter_table('quotation_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_line_items_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('technical_validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_json', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_validation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_validation_runs_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_task_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('original_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('final_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('triggered_rule_ids', app.db.types.JSONDocument(), nullable=False),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_approval_action_id')
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_actions_approval_task_id'), ['approval_task_id'], unique=False)

    op.create_table('combined_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version', sa.Integer(), nullable=False),
    sa.Column('technical_validation_run_id', sa.Integer(), nullable=True),
    sa.Column('commercial_validation_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('recommended_next_action', sa.String(length=200), nullable=False),
    sa.Column('triggered_rule_ids', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_validation_run_id'], ['commercial_validation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technical_validation_run_id'], ['technical_validation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combined_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combined_decisions_quotation_id'), ['quotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combined_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combined_decisions_quotation_id'))

    op.drop_table('combined_decisions')
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_actions_approval_task_id'))

    op.drop_table('approval_actions')
    with op.batch_alter_table('technical_validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_validation_runs_quotation_id'))

    op.drop_table('technical_validation_runs')
    with op.batch_alter_table('quotation_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_line_items_quotation_id'))

    op.drop_table('quotation_line_items')
    with op.batch_alter_table('pricing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_runs_quotation_id'))

    op.drop_table('pricing_runs')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_documents_quotation_id'))

    op.drop_table('generated_documents')
    with op.batch_alter_table('email_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_records_quotation_id'))

    op.drop_table('email_records')
    with op.batch_alter_table('commercial_validation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_validation_runs_quotation_id'))

    op.drop_table('commercial_validation_runs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_quotation_id'))
        batch_op.drop_index('ix_audit_events_event_type')

    op.drop_table('audit_events')
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_tasks_status')
        batch_op.drop_index(batch_op.f('ix_approval_tasks_quotation_id'))

    op.drop_table('approval_tasks')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('ix_quotations_status')
        batch_op.drop_index(batch_op.f('ix_quotations_quotation_id'))
        batch_op.drop_index('ix_quotations_owner_user_id')

    op.drop_table('quotations')
    op.drop_table('pricing_data_versions')
    op.drop_table('users')
    # ### end Alembic commands ###
