"""phase 6 authenticated approval

Revision ID: 5a8d9fabed0b
Revises: 7299ce046f09
Create Date: 2026-08-05 01:57:58.468553
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.types


revision = '5a8d9fabed0b'
down_revision = '7299ce046f09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token'), ['token'], unique=True)
        batch_op.create_index('ix_user_sessions_user_id', ['user_id'], unique=False)

    op.create_table('approval_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_task_id', sa.Integer(), nullable=False),
    sa.Column('approval_action_id', sa.Integer(), nullable=True),
    sa.Column('original_decision', sa.String(length=50), nullable=False),
    sa.Column('evaluated_margin_percent', sa.String(length=32), nullable=False),
    sa.Column('policy_threshold_percent', sa.String(length=32), nullable=False),
    sa.Column('policy_version_id', sa.String(length=120), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('approver_name', sa.String(length=200), nullable=False),
    sa.Column('approver_role', sa.String(length=100), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('final_approved_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('final_margin_percent', sa.String(length=32), nullable=False),
    sa.Column('triggered_rule_ids', app.db.types.JSONDocument(), nullable=False),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_action_id'], ['approval_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_task_id'], ['approval_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_overrides_approval_task_id'), ['approval_task_id'], unique=False)

    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_version', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_reference', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('quotation_reference', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('quotation_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('decision_status', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('submitted_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('pricing_run_id', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('validation_run_id', sa.String(length=64), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_approval_tasks_task_reference'), ['task_reference'], unique=False)
        batch_op.create_foreign_key(
            'fk_approval_tasks_submitted_by_user_id',
            'users',
            ['submitted_by_user_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_role', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('quotation_version', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('request_id', sa.String(length=64), nullable=False, server_default=''))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('external_subject', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_login_at', app.db.types.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('external_subject')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_column('request_id')
        batch_op.drop_column('policy_version_id')
        batch_op.drop_column('quotation_version')
        batch_op.drop_column('actor_role')

    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_approval_tasks_submitted_by_user_id', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_approval_tasks_task_reference'))
        batch_op.drop_column('validation_run_id')
        batch_op.drop_column('pricing_run_id')
        batch_op.drop_column('policy_version_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by_user_id')
        batch_op.drop_column('decision_status')
        batch_op.drop_column('quotation_version')
        batch_op.drop_column('quotation_reference')
        batch_op.drop_column('task_reference')

    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_column('quotation_version')

    with op.batch_alter_table('approval_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_overrides_approval_task_id'))

    op.drop_table('approval_overrides')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_id')
        batch_op.drop_index(batch_op.f('ix_user_sessions_token'))

    op.drop_table('user_sessions')
    # ### end Alembic commands ###
