"""phase 2 excel ingestion

Revision ID: 7299ce046f09
Revises: 0001_initial
Create Date: 2026-08-04 08:15:15.322652
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.types


revision = '7299ce046f09'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_mapping_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset_kind', sa.String(length=50), nullable=False),
    sa.Column('sheet_name', sa.String(length=200), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('definition', app.db.types.JSONDocument(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pricing_data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_kind', sa.String(length=50), nullable=False),
    sa.Column('source_sheet', sa.String(length=200), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=120), nullable=False),
    sa.Column('has_warnings', sa.Boolean(), nullable=False),
    sa.Column('payload', app.db.types.JSONDocument(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['pricing_data_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_data_records', schema=None) as batch_op:
        batch_op.create_index('ix_pricing_data_records_product', ['version_id', 'product_id'], unique=False)
        batch_op.create_index('ix_pricing_data_records_version_dataset', ['version_id', 'dataset_kind'], unique=False)

    op.create_table('pricing_data_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_kind', sa.String(length=50), nullable=False),
    sa.Column('source_sheet', sa.String(length=200), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('issues', app.db.types.JSONDocument(), nullable=False),
    sa.Column('payload', app.db.types.JSONDocument(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['pricing_data_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_data_rejections', schema=None) as batch_op:
        batch_op.create_index('ix_pricing_data_rejections_version', ['version_id'], unique=False)

    with op.batch_alter_table('pricing_data_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_kind', sa.String(length=50), nullable=False, server_default='excel_import'))
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=150), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('uploaded_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('storage_uri', sa.String(length=1000), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('activated_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('warning_row_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rejected_row_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('mapping_profile', app.db.types.JSONDocument(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('validation_summary', app.db.types.JSONDocument(), nullable=False, server_default='{}'))
        batch_op.create_index('ix_pricing_data_versions_checksum', ['checksum'], unique=False)
        batch_op.create_index('ix_pricing_data_versions_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_data_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_pricing_data_versions_is_active')
        batch_op.drop_index('ix_pricing_data_versions_checksum')
        batch_op.drop_column('validation_summary')
        batch_op.drop_column('mapping_profile')
        batch_op.drop_column('rejected_row_count')
        batch_op.drop_column('warning_row_count')
        batch_op.drop_column('activated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('storage_uri')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('source_kind')

    with op.batch_alter_table('pricing_data_rejections', schema=None) as batch_op:
        batch_op.drop_index('ix_pricing_data_rejections_version')

    op.drop_table('pricing_data_rejections')
    with op.batch_alter_table('pricing_data_records', schema=None) as batch_op:
        batch_op.drop_index('ix_pricing_data_records_version_dataset')
        batch_op.drop_index('ix_pricing_data_records_product')

    op.drop_table('pricing_data_records')
    op.drop_table('column_mapping_profiles')
    # ### end Alembic commands ###
