"""phase 8 document generation metadata

Revision ID: a91dba1dbf86
Revises: e908094448e4
Create Date: 2026-08-05 03:14:25.639018
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.types


revision = 'a91dba1dbf86'
down_revision = 'e908094448e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('quotation_reference', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('approval_action_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('template_version', sa.String(length=50), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('document_plan_version', sa.String(length=50), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('agent_provider', sa.String(length=50), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('render_engine', sa.String(length=50), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('generated_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('storage_reference', sa.String(length=300), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False, server_default=sa.text("'generated'")))
        batch_op.add_column(sa.Column('error_category', sa.String(length=50), nullable=False, server_default=sa.text("'none'")))
        batch_op.create_index(batch_op.f('ix_generated_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_status'), ['status'], unique=False)
        batch_op.create_foreign_key(
            'fk_generated_documents_approval_action_id',
            'approval_actions',
            ['approval_action_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_generated_documents_approval_action_id', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_generated_documents_status'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_document_id'))
        batch_op.drop_column('error_category')
        batch_op.drop_column('status')
        batch_op.drop_column('storage_reference')
        batch_op.drop_column('generated_at')
        batch_op.drop_column('render_engine')
        batch_op.drop_column('agent_provider')
        batch_op.drop_column('document_plan_version')
        batch_op.drop_column('template_version')
        batch_op.drop_column('approval_action_id')
        batch_op.drop_column('quotation_reference')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
