"""phase 7 email delivery and reminders

Revision ID: e908094448e4
Revises: 5a8d9fabed0b
Create Date: 2026-08-05 02:32:20.529422
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.db.types


revision = 'e908094448e4'
down_revision = '5a8d9fabed0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_cycle', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('reminder_sent_count', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('reminder_last_sent_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_claimed_at', app.db.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_last_error_category', sa.String(length=32), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('reminder_attempt_count', sa.Integer(), nullable=False, server_default=sa.text("'0'")))

    with op.batch_alter_table('email_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('quotation_reference', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('quotation_version', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('approval_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_type', sa.String(length=50), nullable=False, server_default=sa.text("'approval_request'")))
        batch_op.add_column(sa.Column('sender', sa.String(length=320), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('recipients', app.db.types.JSONDocument(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('cc_recipients', app.db.types.JSONDocument(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('bcc_recipients', app.db.types.JSONDocument(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('body_storage_mode', sa.String(length=20), nullable=False, server_default=sa.text("'hash'")))
        batch_op.add_column(sa.Column('body_hash', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('template_version', sa.String(length=32), nullable=False, server_default=sa.text("'v1'")))
        batch_op.add_column(sa.Column('agent_provider', sa.String(length=50), nullable=False, server_default=sa.text("'deterministic'")))
        batch_op.add_column(sa.Column('agent_fallback_used', sa.Boolean(), nullable=False, server_default=sa.text("'1'")))
        batch_op.add_column(sa.Column('agent_fallback_reason', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('delivery_provider', sa.String(length=50), nullable=False, server_default=sa.text("'console'")))
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('last_error_category', sa.String(length=32), nullable=False, server_default=sa.text("'none'")))
        batch_op.add_column(sa.Column('last_error_detail', sa.Text(), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=200), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=200), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('attachment_document_ids', app.db.types.JSONDocument(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('reminder_cycle', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_records_email_id'), ['email_id'], unique=True)
        batch_op.create_index('ix_email_records_status', ['status'], unique=False)
        batch_op.create_unique_constraint('uq_email_idempotency_key', ['idempotency_key'])
        batch_op.create_foreign_key('fk_email_records_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_email_records_approval_task_id', 'approval_tasks', ['approval_task_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('error')
        batch_op.drop_column('queued_at')
        batch_op.drop_column('provider')
        batch_op.drop_column('recipient')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.VARCHAR(length=50), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('recipient', sa.VARCHAR(length=320), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=50), nullable=False, server_default=sa.text("'local'")))
        batch_op.add_column(sa.Column('queued_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.TEXT(), nullable=False, server_default=sa.text("''")))
        batch_op.drop_constraint(
            'fk_email_records_approval_task_id', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'fk_email_records_created_by_user_id', type_='foreignkey'
        )
        batch_op.drop_constraint('uq_email_idempotency_key', type_='unique')
        batch_op.drop_index('ix_email_records_status')
        batch_op.drop_index(batch_op.f('ix_email_records_email_id'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('reminder_cycle')
        batch_op.drop_column('attachment_document_ids')
        batch_op.drop_column('provider_message_id')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('last_error_detail')
        batch_op.drop_column('last_error_category')
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('delivery_provider')
        batch_op.drop_column('agent_fallback_reason')
        batch_op.drop_column('agent_fallback_used')
        batch_op.drop_column('agent_provider')
        batch_op.drop_column('template_version')
        batch_op.drop_column('body_hash')
        batch_op.drop_column('body_storage_mode')
        batch_op.drop_column('bcc_recipients')
        batch_op.drop_column('cc_recipients')
        batch_op.drop_column('recipients')
        batch_op.drop_column('sender')
        batch_op.drop_column('email_type')
        batch_op.drop_column('approval_task_id')
        batch_op.drop_column('quotation_version')
        batch_op.drop_column('quotation_reference')
        batch_op.drop_column('email_id')

    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder_attempt_count')
        batch_op.drop_column('reminder_last_error_category')
        batch_op.drop_column('reminder_claimed_at')
        batch_op.drop_column('reminder_last_sent_at')
        batch_op.drop_column('reminder_sent_count')
        batch_op.drop_column('reminder_cycle')

    # ### end Alembic commands ###
